<template>
  <div class="space-y-4">
    <div class="space-y-2">
      <div class="flex items-center justify-between gap-2">
        <h3 class="text-sm font-medium text-muted-foreground">Description</h3>
        <div v-if="asset && draft && isEditing && !needsReview" class="flex items-center gap-2">
          <Button variant="ghost" size="sm" :disabled="isSaving" @click="$emit('cancel-edit')">
            Cancel
          </Button>
          <Transition
            enter-active-class="transition-opacity duration-200"
            leave-active-class="transition-opacity duration-200"
            enter-from-class="opacity-0"
            leave-to-class="opacity-0"
          >
            <Button
              v-if="hasChanges"
              variant="outline"
              size="sm"
              :disabled="isSaving || !hasChanges"
              :is-loading="isSaving"
              @click="$emit('save')"
            >
              <template #loading>Saving...</template>
              Save
            </Button>
          </Transition>
        </div>
      </div>

      <div v-if="needsReview" class="space-y-3">
        <Alert v-if="asset.ai_flag_reason">
          <Info />
          <AlertTitle class="line-clamp-none">{{ asset.ai_flag_reason }} </AlertTitle>
          <AlertDescription>
            This note was generated by Myriade and will disappear after approving.
          </AlertDescription>
        </Alert>

        <Alert v-else>
          <Info />
          <AlertTitle>This description requires validation</AlertTitle>
          <AlertDescription>
            This note was generated by Myriade and will disappear after approving.
          </AlertDescription>
        </Alert>

        <!-- Git-style unified diff view (only if there's an actual AI suggestion) -->
        <div v-if="asset.ai_suggestion" class="overflow-hidden bg-card border rounded-md">
          <div class="space-y-0 text-xs font-mono leading-relaxed">
            <!-- Before (removal) -->
            <div class="bg-red-50 dark:bg-red-900/20 px-2 py-1 border-l-2 border-red-400">
              <span class="text-red-600 select-none mr-2">−</span>
              <span class="text-red-900 dark:text-red-200">{{ asset.description || '' }}</span>
            </div>
            <!-- After (addition) - Editable -->
            <div class="bg-green-50 dark:bg-green-900/20 px-2 py-1 border-l-2 border-green-400">
              <span class="text-green-600 select-none mr-2">+</span>
              <Textarea
                :model-value="editableSuggestion"
                @update:model-value="updateEditableSuggestion"
                rows="3"
                class="inline-block align-top w-[calc(100%-1.5rem)] border-0 p-0 text-xs font-mono text-green-900 dark:text-green-200 bg-transparent focus:ring-0 focus:ring-offset-0 focus:outline-none focus:border-0 focus-visible:ring-0 focus-visible:ring-offset-0 resize-none leading-relaxed shadow-none"
                :disabled="isSaving"
                placeholder="Edit AI suggestion..."
              />
            </div>
          </div>
        </div>

        <!-- If no AI suggestion, just show editable textarea -->
        <Textarea
          v-else
          :model-value="editableSuggestion"
          @update:model-value="updateEditableSuggestion"
          rows="5"
          class="rounded-lg"
          :disabled="isSaving"
          placeholder="Edit description..."
        />
      </div>

      <!-- Regular description view/edit (all other statuses) -->
      <div v-else>
        <!-- Read-only markdown view when not editing -->
        <div
          v-if="!isEditing && draft.description"
          class="prose prose-sm max-w-none p-3 rounded-lg border border-border bg-muted/30 cursor-pointer hover:bg-muted transition-colors"
          @click="$emit('start-edit')"
        >
          <MarkdownDisplay :content="draft.description" class="text-sm" />
        </div>
        <!-- Editable textarea when editing or no description -->
        <Textarea
          v-else
          :model-value="draft.description"
          @update:model-value="updateDescription"
          rows="5"
          class="rounded-lg"
          :disabled="isSaving"
          @focus="$emit('start-edit')"
          placeholder="Click to add description..."
        />
      </div>

      <p v-if="error" class="text-sm text-destructive">
        {{ error }}
      </p>
    </div>

    <!-- Tags Section with diff (only in needsReview mode and if there are suggested tags) -->
    <div
      v-if="needsReview && asset.ai_suggested_tags && asset.ai_suggested_tags.length > 0"
      class="space-y-2 w-full flex-1"
    >
      <h3 class="text-sm font-medium text-muted-foreground">Tags</h3>

      <!-- Git-style unified diff view for tags -->
      <div class="overflow-hidden bg-card border rounded-md">
        <div class="space-y-0">
          <!-- Before (removal) - Current tags -->
          <div class="bg-red-50 dark:bg-red-900/20 px-3 py-2 border-l-2 border-red-400">
            <div class="flex items-center gap-2 flex-wrap">
              <span class="text-red-600 select-none">−</span>
              <div v-if="asset.tags.length > 0" class="flex items-center gap-1 flex-wrap">
                <Badge
                  v-for="tag in asset.tags"
                  :key="tag.id"
                  variant="outline"
                  class="text-red-900 dark:text-red-200 border-red-200"
                >
                  {{ tag.name }}
                </Badge>
              </div>
              <span v-else class="text-red-900 dark:text-red-200 text-sm italic">No tags</span>
            </div>
          </div>
          <!-- After (addition) - Show only NEW suggested tags in diff -->
          <div
            v-if="newSuggestedTagsForDiff.length > 0"
            class="bg-green-50 dark:bg-green-900/20 px-3 py-2 border-l-2 border-green-400"
          >
            <div class="flex items-center gap-2 flex-wrap">
              <span class="text-green-600 select-none">+</span>
              <div class="flex items-center gap-1 flex-wrap">
                <Badge
                  v-for="tag in newSuggestedTagsForDiff"
                  :key="tag.id"
                  variant="outline"
                  class="text-green-900 dark:text-green-200 border-green-200"
                >
                  {{ tag.name }}
                </Badge>
              </div>
            </div>
          </div>
          <!-- Edit all tags section (shown separately) -->
          <div class="px-3 py-2 border-t border-gray-200">
            <label class="text-xs font-medium text-muted-foreground mb-2 block">Edit Tags</label>
            <AssetTagSelect
              v-model="editableSuggestedTags"
              :disabled="isSaving"
              class="bg-transparent border-0"
            />
          </div>
        </div>
      </div>
    </div>

    <!-- Regular tags section (when not in needsReview mode or no suggested tags) -->
    <div v-else class="space-y-2 w-full flex-1">
      <h3 class="text-sm font-medium text-muted-foreground">Tags</h3>
      <AssetTagSelect
        :model-value="draft.tags"
        @update:model-value="updateTags"
        class="w-full flex-1"
        :disabled="isSaving"
        @focus="$emit('start-edit')"
      />
    </div>

    <!-- Action buttons (only shown in needsReview mode) -->
    <div v-if="needsReview" class="flex justify-end gap-2 pt-2">
      <Button @click="handleDismissFlag" size="sm" variant="outline" :disabled="isSaving">
        Undo
      </Button>
      <Button
        @click="handleApproveEditedSuggestion"
        size="sm"
        :disabled="isSaving || !editableSuggestion.trim()"
        :is-loading="isSaving"
      >
        <template #loading>Approving...</template>
        Approve
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import AssetTagSelect from '@/components/AssetTagSelect.vue'
import MarkdownDisplay from '@/components/MarkdownDisplay.vue'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { useCatalogStore, type AssetTag, type CatalogAsset } from '@/stores/catalog'
import { computed, ref, watch } from 'vue'
import type { EditableDraft } from './types'
import { Info } from 'lucide-vue-next'

interface Props {
  asset: CatalogAsset
  draft: EditableDraft
  isEditing: boolean
  isSaving: boolean
  hasChanges: boolean
  error: string | null
}

const props = defineProps<Props>()

const emit = defineEmits<{
  'start-edit': []
  'cancel-edit': []
  save: []
  'update:draft': [draft: EditableDraft]
  'dismiss-flag': []
  'approve-suggestion': [payload: { description: string; tagIds: string[] }]
}>()

const catalogStore = useCatalogStore()

const needsReview = computed(() => {
  return ['needs_review', 'requires_validation'].includes(props.asset.status || '')
})

const editableSuggestion = ref(
  props.asset.ai_suggestion || (needsReview.value ? props.asset.description || '' : '')
)

// Convert suggested tag names to AssetTag objects by looking up existing tags
// Merge existing tags + new suggested tags
function initializeEditableSuggestedTags(): AssetTag[] {
  if (props.asset.ai_suggested_tags && needsReview.value) {
    const existingTags = [...(props.asset.tags || [])]
    const suggestedTags = props.asset.ai_suggested_tags
      .map((tagName) =>
        catalogStore.tagsArray.find((t) => t.name.toLowerCase() === tagName.toLowerCase())
      )
      .filter((tag): tag is AssetTag => tag !== undefined)

    // Merge: existing tags + new suggested tags (avoid duplicates)
    const existingTagIds = new Set(existingTags.map((t) => t.id))
    const newSuggestedTags = suggestedTags.filter((tag) => !existingTagIds.has(tag.id))
    return [...existingTags, ...newSuggestedTags]
  }
  return []
}

const editableSuggestedTags = ref<AssetTag[]>(initializeEditableSuggestedTags())

// Computed: Only show NEW suggested tags in diff (tags not already in asset.tags)
const newSuggestedTagsForDiff = computed(() => {
  if (!needsReview.value || !props.asset.ai_suggested_tags) return []

  const existingTagIds = new Set(props.asset.tags.map((t: AssetTag) => t.id))
  return editableSuggestedTags.value.filter((tag: AssetTag) => !existingTagIds.has(tag.id))
})

watch(
  () => [props.asset.ai_suggestion, props.asset.description, props.asset.status] as const,
  ([newSuggestion, newDescription, newStatus]) => {
    const isReviewStatus = ['needs_review', 'requires_validation'].includes(newStatus || '')
    editableSuggestion.value = newSuggestion || (isReviewStatus ? newDescription || '' : '')
  }
)

watch(
  () => [props.asset.ai_suggested_tags, props.asset.status, props.asset.tags] as const,
  ([newSuggestedTags, newStatus, currentTags]) => {
    const isReviewStatus = ['needs_review', 'requires_validation'].includes(newStatus || '')
    if (newSuggestedTags && isReviewStatus) {
      const existingTags = [...(currentTags || [])]
      const suggestedTags = newSuggestedTags
        .map((tagName) =>
          catalogStore.tagsArray.find((t) => t.name.toLowerCase() === tagName.toLowerCase())
        )
        .filter((tag): tag is AssetTag => tag !== undefined)

      // Merge: existing tags + new suggested tags (avoid duplicates)
      const existingTagIds = new Set(existingTags.map((t) => t.id))
      const newSuggestedTagsOnly = suggestedTags.filter((tag) => !existingTagIds.has(tag.id))
      editableSuggestedTags.value = [...existingTags, ...newSuggestedTagsOnly]
    } else {
      editableSuggestedTags.value = []
    }
  }
)

function updateDescription(description: string | number) {
  emit('update:draft', { ...props.draft, description: String(description) })
  emit('start-edit')
}

function updateTags(tags: AssetTag[]) {
  emit('update:draft', { ...props.draft, tags })
  emit('start-edit')
}

function updateEditableSuggestion(value: string | number) {
  editableSuggestion.value = String(value)
}

function handleDismissFlag() {
  emit('dismiss-flag')
}

function handleApproveEditedSuggestion() {
  if (!editableSuggestion.value.trim()) return

  // Use edited suggested tags if available, otherwise use existing tags
  const tagIds =
    editableSuggestedTags.value.length > 0
      ? editableSuggestedTags.value.map((tag: AssetTag) => tag.id).filter((id: string) => id) // Filter out empty IDs from suggested tags
      : props.asset.tags.map((tag: AssetTag) => tag.id)

  emit('approve-suggestion', {
    description: editableSuggestion.value.trim(),
    tagIds
  })
}
</script>
