<template>
  <Card
    :class="
      cn(
        'transition-shadow rounded-xl hover:border-primary-600',
        props.selected ? 'ring-2 ring-primary-500 shadow-md' : ''
      )
    "
    :id="props.asset.id"
  >
    <CardHeader>
      <CardTitle class="flex items-center gap-2">
        <component :is="iconByType[props.asset.type]" class="w-5 h-5" />
        <span>{{ props.asset.name }}</span>
      </CardTitle>
      <CardDescription class="flex flex-wrap items-center gap-1">
        <Badge
          :class="
            cn(
              props.asset.type === 'TABLE'
                ? 'bg-blue-100 text-blue-800'
                : 'bg-green-100 text-green-800'
            )
          "
          >{{ props.asset.type }}</Badge
        >

        <p v-if="props.asset.type === 'COLUMN'" class="text-sm text-muted-foreground">
          from {{ columnOrigin }}
        </p>
        <p v-else-if="props.asset.type === 'TABLE'" class="text-sm text-muted-foreground">
          from {{ props.asset.schema }}
        </p>
      </CardDescription>
      <CardAction class="flex flex-wrap items-center justify-end gap-2">
        <!-- Status Badge -->
        <AssetBadgeStatus :status="props.asset.status" />

        <!-- Navigate to catalog button -->
        <Button
          variant="ghost"
          size="icon"
          class="text-muted-foreground"
          :disabled="isProcessing"
          @click="handleNavigateToCatalog"
        >
          <span class="sr-only">Open asset in catalog</span>
          <ExternalLink class="w-4 h-4" />
        </Button>
      </CardAction>
    </CardHeader>
    <CardContent>
      <!-- Description Edit -->
      <div class="space-y-2">
        <label class="text-xs font-medium text-muted-foreground">Description</label>

        <!-- Needs review/validation statuses -->
        <div v-if="needsReview" class="space-y-3">
          <!-- AI Flag Reason Alert -->
          <Alert v-if="props.asset.ai_flag_reason">
            <Info />
            <AlertTitle class="line-clamp-none">{{ props.asset.ai_flag_reason }} </AlertTitle>
            <AlertDescription>
              This note was generated by Myriade and will disappear after approving.
            </AlertDescription>
          </Alert>

          <Alert v-else>
            <Info />
            <AlertTitle>This description requires validation</AlertTitle>
            <AlertDescription>
              This note was generated by Myriade and will disappear after approving.
            </AlertDescription>
          </Alert>

          <!-- Git-style unified diff view (only if there's an actual AI suggestion) -->
          <div v-if="props.asset.ai_suggestion" class="overflow-hidden bg-white border rounded-md">
            <div class="space-y-0 text-xs font-mono leading-relaxed">
              <!-- Before (removal) -->
              <div class="bg-red-50 px-2 py-1 border-l-2 border-red-400">
                <span class="text-red-600 select-none mr-2">−</span>
                <span class="text-red-900">{{ props.asset.description || '' }}</span>
              </div>
              <!-- After (addition) - Editable -->
              <div class="bg-green-50 px-2 py-1 border-l-2 border-green-400">
                <span class="text-green-600 select-none mr-2">+</span>
                <Textarea
                  v-model="draft.description"
                  rows="3"
                  class="inline-block align-top w-[calc(100%-1.5rem)] border-0 p-0 text-xs font-mono text-green-900 bg-transparent focus:ring-0 focus:ring-offset-0 focus:outline-none focus:border-0 focus-visible:ring-0 focus-visible:ring-offset-0 resize-none leading-relaxed shadow-none"
                  :disabled="isProcessing"
                  placeholder="Edit AI suggestion..."
                />
              </div>
            </div>
          </div>

          <!-- If no AI suggestion, just show editable textarea -->
          <Textarea
            v-else
            v-model="draft.description"
            rows="5"
            class="rounded-lg"
            :disabled="isProcessing"
            placeholder="Edit description..."
          />
        </div>

        <Textarea
          v-else
          v-model="draft.description"
          rows="4"
          class="max-h-72"
          :disabled="isProcessing"
        />
      </div>

      <div
        v-if="
          needsReview && props.asset.ai_suggested_tags && props.asset.ai_suggested_tags.length > 0
        "
        class="space-y-2"
      >
        <label class="text-xs font-medium text-muted-foreground">Tags</label>

        <div class="overflow-hidden bg-white border rounded-md">
          <div class="space-y-0">
            <div class="bg-red-50 px-3 py-2 border-l-2 border-red-400">
              <div class="flex items-center gap-2 flex-wrap">
                <span class="text-red-600 select-none">−</span>
                <div v-if="props.asset.tags.length > 0" class="flex items-center gap-1 flex-wrap">
                  <Badge
                    v-for="tag in props.asset.tags"
                    :key="tag.id"
                    variant="outline"
                    class="text-red-900 border-red-200"
                  >
                    {{ tag.name }}
                  </Badge>
                </div>
                <span v-else class="text-red-900 text-sm italic">No tags</span>
              </div>
            </div>
            <div
              v-if="newSuggestedTagsForDiff.length > 0"
              class="bg-green-50 px-3 py-2 border-l-2 border-green-400"
            >
              <div class="flex items-center gap-2 flex-wrap">
                <span class="text-green-600 select-none">+</span>
                <div class="flex items-center gap-1 flex-wrap">
                  <Badge
                    v-for="tag in newSuggestedTagsForDiff"
                    :key="tag.id"
                    variant="outline"
                    class="text-green-900 border-green-200"
                  >
                    {{ tag.name }}
                  </Badge>
                </div>
              </div>
            </div>
            <!-- Edit all tags section (shown separately) -->
            <div class="px-3 py-2 border-t border-gray-200">
              <label class="text-xs font-medium text-muted-foreground mb-2 block">Edit Tags</label>
              <AssetTagSelect
                v-model="draft.tags"
                :disabled="isProcessing"
                class="bg-transparent border-0"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Tags Section: Regular display (always show unless in diff mode) -->
      <div v-else class="space-y-2">
        <label class="text-xs font-medium text-muted-foreground">Tags</label>
        <AssetTagSelect v-model="draft.tags" :disabled="isProcessing" />
      </div>

      <div v-if="needsReview" class="flex justify-end gap-2 pt-2">
        <Button @click="handleDismissFlag" size="sm" variant="outline" :disabled="isProcessing">
          Undo
        </Button>
        <Button
          @click="handleSave"
          size="sm"
          :disabled="isProcessing || !draft.description.trim()"
          :is-loading="isProcessing"
        >
          <template #loading>Approving...</template>
          Approve
        </Button>
      </div>

      <!-- Save button for non-review mode (when there are changes) -->
      <div v-if="!needsReview && hasChanges" class="flex justify-end gap-2 pt-2">
        <Button @click="handleSave" size="sm" :disabled="isProcessing" :is-loading="isProcessing">
          <template #loading>Saving...</template>
          Save
        </Button>
      </div>
    </CardContent>
  </Card>
</template>

<script lang="ts" setup>
import { cn } from '@/lib/utils'
import {
  useCatalogStore,
  type AssetStatus,
  type AssetTag,
  type AssetType,
  type CatalogAsset,
  type Privacy
} from '@/stores/catalog'
import { useContextsStore } from '@/stores/contexts'
import { useQueryClient } from '@tanstack/vue-query'
import { Columns3, Database, ExternalLink, Info } from 'lucide-vue-next'
import { computed, reactive, ref, watch, type Component } from 'vue'
import { Alert, AlertDescription, AlertTitle } from './ui/alert'
import { Badge } from './ui/badge'
import { Button } from './ui/button'
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card'
import { Textarea } from './ui/textarea'
import AssetBadgeStatus from './AssetBadgeStatus.vue'
import AssetTagSelect from './AssetTagSelect.vue'

interface AssetInput {
  id: string
  type: AssetType
  name: string
  description?: string | null
  dataType?: string | null
  privacy?: Privacy
  tags: AssetTag[]
  schema?: string | null
  tableName?: string | null
  status?: AssetStatus
  ai_suggestion?: string | null
  ai_flag_reason?: string | null
  ai_suggested_tags?: string[] | null
}

const props = defineProps<{
  asset: AssetInput
  isProcessing?: boolean
  selected?: boolean
}>()

const emit = defineEmits<{
  (
    e: 'approve',
    payload: {
      id: string
      description: string
      tag_ids: string[]
      approve_suggestion?: boolean
      ai_suggestion?: null
      ai_flag_reason?: null
      ai_suggested_tags?: null
    }
  ): void
  (e: 'navigate-to-catalog', payload: { id: string }): void
}>()

const catalogStore = useCatalogStore()
const contextsStore = useContextsStore()
const queryClient = useQueryClient()
const approving = ref(false)
const isProcessing = computed(() => (props.isProcessing ?? false) || approving.value)

const iconByType: Record<AssetType, Component> = {
  TABLE: Database,
  COLUMN: Columns3
}

const needsReview = computed(() =>
  ['needs_review', 'requires_validation'].includes(props.asset.status || '')
)

const columnOrigin = computed(() => {
  if (props.asset.type !== 'COLUMN') return ''

  const schema = props.asset.schema?.trim()
  const tableName = props.asset.tableName?.trim()

  if (schema && tableName) return `${schema}.${tableName}`
  if (tableName) return tableName
  if (schema) return schema

  return 'Unknown table'
})

const draft = reactive({
  description: '',
  tags: [] as AssetTag[]
})

// Initialize draft when asset changes or when tags are loaded
watch(
  () => [props.asset, catalogStore.tagsArray] as const,
  ([asset, tagsArray]) => {
    draft.description =
      needsReview.value && asset.ai_suggestion?.trim()
        ? asset.ai_suggestion
        : asset.description || ''

    if (needsReview.value && asset.ai_suggested_tags && asset.ai_suggested_tags.length > 0) {
      const existingTags = [...(asset.tags || [])]

      if (tagsArray.length > 0) {
        const suggestedTags = asset.ai_suggested_tags
          .map((tagName) => tagsArray.find((t) => t.name.toLowerCase() === tagName.toLowerCase()))
          .filter((tag): tag is AssetTag => tag !== undefined)

        const existingTagIds = new Set(existingTags.map((t) => t.id))
        const newSuggestedTags = suggestedTags.filter((tag) => !existingTagIds.has(tag.id))
        draft.tags = [...existingTags, ...newSuggestedTags]
      } else {
        draft.tags = existingTags
      }
    } else {
      draft.tags = asset?.tags || []
    }
  },
  { immediate: true }
)

const newSuggestedTagsForDiff = computed(() => {
  if (!needsReview.value || !props.asset.ai_suggested_tags) return []

  const existingTagIds = new Set(props.asset.tags.map((t) => t.id))
  return draft.tags.filter((tag) => !existingTagIds.has(tag.id))
})

const hasChanges = computed(() => {
  if (needsReview.value) return true

  const descChanged = draft.description.trim() !== (props.asset.description || '').trim()
  const tagsChanged =
    draft.tags.length !== props.asset.tags.length ||
    draft.tags.some((tag, i) => tag.id !== props.asset.tags[i]?.id)

  return descChanged || tagsChanged
})

function handleSave() {
  if (!hasChanges.value) return

  // If approving AI suggestions, add the approve_suggestion flag
  if (props.asset.ai_suggestion || props.asset.ai_flag_reason || props.asset.ai_suggested_tags) {
    emit('approve', {
      id: props.asset.id,
      description: draft.description.trim(),
      tag_ids: draft.tags.map((tag) => tag.id).filter((id) => id), // Filter out empty IDs from suggested tags
      approve_suggestion: true,
      ai_suggestion: null,
      ai_flag_reason: null,
      ai_suggested_tags: null
    })
  } else {
    emit('approve', {
      id: props.asset.id,
      description: draft.description.trim(),
      tag_ids: draft.tags.map((tag) => tag.id).filter((id) => id)
    })
  }
}

function handleNavigateToCatalog() {
  emit('navigate-to-catalog', { id: props.asset.id })
}

async function handleDismissFlag() {
  try {
    approving.value = true
    const updated = await catalogStore.dismissFlag(props.asset.id)

    // Update the query cache directly instead of refetching
    const queryKey = ['catalog', 'assets', contextsStore.contextSelected?.id]
    queryClient.setQueryData(queryKey, (oldData: CatalogAsset[] | undefined) => {
      if (!oldData) return oldData
      return oldData.map((a) => (a.id === updated.id ? updated : a))
    })
  } catch (error) {
    console.error('Failed to dismiss flag', error)
  } finally {
    approving.value = false
  }
}
</script>
