"""Update Semantic Catalog

Revision ID: 0ddb62127752
Revises: 6f6798d12b46
Create Date: 2025-05-15 10:38:45.043162

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ddb62127752"
down_revision: Union[str, None] = "6f6798d12b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_entity", sa.Column("database_id", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE business_entity SET database_id = 1 WHERE database_id IS NULL")
    op.alter_column("business_entity", "database_id", nullable=False)
    op.add_column(
        "business_entity",
        sa.Column("review_conversation_id", sa.String(), nullable=True),
    )
    op.create_foreign_key(None, "business_entity", "database", ["database_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "business_entity", type_="foreignkey")
    op.drop_column("business_entity", "review_conversation_id")
    op.drop_column("business_entity", "database_id")
    # ### end Alembic commands ###
