"""Add sensitive_data_mapping

Revision ID: 19374c61b90a
Revises: c1f41610cac4
Create Date: 2025-04-25 11:29:40.514298

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19374c61b90a"
down_revision: Union[str, None] = "c1f41610cac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensitive_data_mapping",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("generated_id", sa.String(), nullable=False),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("hash"),
        sa.UniqueConstraint("generated_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensitive_data_mapping")
    # ### end Alembic commands ###
