"""Update Semantic Catalog

Revision ID: 198bd150d1a3
Revises: 0ddb62127752
Create Date: 2025-05-15 10:51:36.554449

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "198bd150d1a3"
down_revision: Union[str, None] = "0ddb62127752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business_entity",
        "review_conversation_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="review_conversation_id::integer",
    )
    op.create_foreign_key(
        None, "business_entity", "conversation", ["review_conversation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "business_entity", type_="foreignkey")
    op.alter_column(
        "business_entity",
        "review_conversation_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        # No USING needed for int to varchar typically, but good to be aware
        # postgresql_using='review_conversation_id::varchar' # If needed for downgrade
    )
    # ### end Alembic commands ###
