"""Update Issue

Revision ID: 1c0c28caebb5
Revises: 198bd150d1a3
Create Date: 2025-05-15 18:21:20.023149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c0c28caebb5"
down_revision: Union[str, None] = "198bd150d1a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "DONE", name="status"),
            nullable=False,
        ),
        sa.Column("database_id", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("business_entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["business_entity_id"],
            ["business_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["database_id"],
            ["database.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["conversation_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "business_entity",
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "business_entity",
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business_entity", "updatedAt")
    op.drop_column("business_entity", "createdAt")
    op.drop_table("issues")
    # ### end Alembic commands ###
