"""Remove privacy mode

Revision ID: 2290e3135f5b
Revises: 19374c61b90a
Create Date: 2025-04-26 19:22:08.406308

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2290e3135f5b"
down_revision: Union[str, None] = "19374c61b90a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("database", "privacy_mode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "database",
        sa.Column(
            "privacy_mode",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
