"""Update BusinessEntities, Issue

Revision ID: 2ba0d4f73bb9
Revises: 942ce66a2f69
Create Date: 2025-05-17 08:06:56.168652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ba0d4f73bb9"
down_revision: Union[str, None] = "942ce66a2f69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add issuescope enum
    op.execute("CREATE TYPE issuescope AS ENUM ('DATA', 'BUSINESS', 'BOTH', 'UNKNOWN')")
    # add severity enum
    op.execute("CREATE TYPE severity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business_entity", sa.Column("definition", sa.Text(), nullable=True))
    op.add_column("business_entity", sa.Column("table_ref", sa.String(), nullable=True))
    op.drop_column("business_entity", "recommendations")
    op.add_column(
        "issues",
        sa.Column(
            "scope",
            sa.Enum("DATA", "BUSINESS", "BOTH", "UNKNOWN", name="issuescope"),
            nullable=True,
        ),
    )
    op.add_column(
        "issues",
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity"),
            nullable=True,
        ),
    )
    op.drop_column("issues", "priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    # drop issuescope enum
    op.execute("DROP TYPE issuescope")
    # drop severity enum
    op.execute("DROP TYPE severity")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issues",
        sa.Column(
            "priority",
            postgresql.ENUM(
                "LOW", "MEDIUM", "HIGH", "CRITICAL", "BLOCKER", name="priority"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("issues", "severity")
    op.drop_column("issues", "scope")
    op.add_column(
        "business_entity",
        sa.Column(
            "recommendations",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("business_entity", "table_ref")
    op.drop_column("business_entity", "definition")
    # ### end Alembic commands ###
