"""Add chart

Revision ID: 38ee2d062b18
Revises: c94b363b19c4
Create Date: 2025-03-24 10:09:34.160162

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38ee2d062b18"
down_revision: Union[str, None] = "c94b363b19c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("queryId", sa.Integer(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["queryId"],
            ["query.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "conversation_message", sa.Column("chartId", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "conversation_message", "chart", ["chartId"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversation_message", type_="foreignkey")
    op.drop_column("conversation_message", "chartId")
    op.drop_table("chart")
    # ### end Alembic commands ###
