"""Add Semantic Catalog

Revision ID: 6f6798d12b46
Revises: 2290e3135f5b
Create Date: 2025-05-14 22:16:18.029569

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from back.utils import JSONB

# revision identifiers, used by Alembic.
revision: str = "6f6798d12b46"
down_revision: Union[str, None] = "2290e3135f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("completeness", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("recommendations", JSONB(), nullable=True),
        sa.Column("review_date", sa.DateTime(), nullable=True),
        sa.Column("report", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_entity_name"), "business_entity", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_business_entity_name"), table_name="business_entity")
    op.drop_table("business_entity")
    # ### end Alembic commands ###
