"""Remove visualisationParams

Revision ID: 7d5fe1edcb39
Revises: a5d6abd45408
Create Date: 2025-03-15 19:45:29.560141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d5fe1edcb39"
down_revision: Union[str, None] = "a5d6abd45408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "visualisationParams")
    op.drop_column("user", "is_admin")
    op.drop_column("user", "pictureUrl")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("pictureUrl", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "query",
        sa.Column(
            "visualisationParams",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
