"""add metadata

Revision ID: 8c6487931db9
Revises: a6374eeef0a7
Create Date: 2025-07-15 13:23:26.538888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c6487931db9"
down_revision: Union[str, None] = "a6374eeef0a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata",
        sa.Column(
            "instance_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.execute("INSERT INTO metadata (instance_id) VALUES (gen_random_uuid())")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metadata")
    # ### end Alembic commands ###
