"""add metadata

Revision ID: 8c6487931db9
Revises: a6374eeef0a7
Create Date: 2025-07-15 13:23:26.538888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c6487931db9"
down_revision: Union[str, None] = "a6374eeef0a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create table first
    op.create_table(
        "metadata",
        sa.Column(
            "instance_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(),
            server_default=sa.func.current_timestamp(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )

    # Then use model with session
    from sqlalchemy.orm import Session

    from models import Metadata

    bind = op.get_bind()
    session = Session(bind=bind)

    # Create and save instance
    metadata_instance = Metadata()  # UUID will be auto-generated
    session.add(metadata_instance)
    session.commit()
    session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metadata")
    # ### end Alembic commands ###
