"""Update Issue

Revision ID: 942ce66a2f69
Revises: 1c0c28caebb5
Create Date: 2025-05-15 19:52:58.828407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # Import postgresql dialect

# revision identifiers, used by Alembic.
revision: str = "942ce66a2f69"
down_revision: Union[str, None] = "1c0c28caebb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM variants based on your Python Priority Enum
priority_variants = ("LOW", "MEDIUM", "HIGH", "CRITICAL", "BLOCKER")
priority_enum_type = postgresql.ENUM(
    *priority_variants, name="priority", create_type=True
)


def upgrade() -> None:
    # Create the ENUM type in PostgreSQL
    priority_enum_type.create(
        op.get_bind(), checkfirst=True
    )  # checkfirst=True makes it idempotent

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issues",
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", "BLOCKER", name="priority"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issues", "priority")
    # ### end Alembic commands ###
    # Drop the ENUM type from PostgreSQL
    priority_enum_type.drop(op.get_bind(), checkfirst=True)
