"""add dbt_repo_path to database table

Revision ID: 9addce233509
Revises: c3dae8db7eae
Create Date: 2025-09-10 09:47:13.076182

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9addce233509"
down_revision: Union[str, None] = "c3dae8db7eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("database", sa.Column("dbt_repo_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("database", "dbt_repo_path")
    # ### end Alembic commands ###
