"""Add admin

Revision ID: a5d6abd45408
Revises: 993871236cde
Create Date: 2025-02-13 19:19:43.415273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5d6abd45408"
down_revision: Union[str, None] = "993871236cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # Set admin@localhost as admin
    op.execute("UPDATE \"user\" SET is_admin = true WHERE email = 'admin@localhost'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
