"""add admin rights

Revision ID: a6374eeef0a7
Revises: 9a791d3682e7
Create Date: 2025-07-11 16:56:54.683202

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6374eeef0a7"
down_revision: Union[str, None] = "9a791d3682e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add or update user "admin@localhost" with has_active_subscription
    op.execute(
        "INSERT INTO \"user\" (id, email, has_active_subscription) VALUES ('admin', 'admin@localhost', true) ON CONFLICT (email) DO UPDATE SET has_active_subscription = true"  # noqa: E501
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
