"""Add active subscription

Revision ID: bcf2d29109ad
Revises: add_user_favorites
Create Date: 2025-06-03 17:09:08.609498

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcf2d29109ad"
down_revision: Union[str, None] = "add_user_favorites"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "has_active_subscription",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_active_subscription")
    # ### end Alembic commands ###
