"""Rework Query fields

Revision ID: be42ad21b0c9
Revises: 38ee2d062b18
Create Date: 2025-04-09 18:44:01.322022

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be42ad21b0c9"
down_revision: Union[str, None] = "38ee2d062b18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chart",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.add_column(
        "query",
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("query", sa.Column("count", sa.Integer(), nullable=True))
    op.add_column("query", sa.Column("exception", sa.String(), nullable=True))
    op.drop_constraint("query_creatorId_fkey", "query", type_="foreignkey")
    op.drop_column("query", "tag")
    op.drop_column("query", "creatorId")
    op.drop_column("query", "result")
    op.drop_column("query", "wheres")
    op.drop_column("query", "tables")
    op.drop_column("query", "comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query", sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "query", sa.Column("tables", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "query", sa.Column("wheres", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "query",
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "query",
        sa.Column("creatorId", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "query", sa.Column("tag", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "query_creatorId_fkey", "query", "user", ["creatorId"], ["id"]
    )
    op.drop_column("query", "exception")
    op.drop_column("query", "count")
    op.drop_column("query", "rows")
    op.alter_column(
        "chart",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###
