"""Remove embedding col

Revision ID: c94b363b19c4
Revises: 7d5fe1edcb39
Create Date: 2025-03-17 15:12:19.108260

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c94b363b19c4"
down_revision: Union[str, None] = "7d5fe1edcb39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query",
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
