name: Release

on:
  workflow_run:
    workflows: ["Ruff, Test"]
    types: [completed]
    branches: [master]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "service/pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "./service/uv.lock"
      - name: Install semantic-release
        run: |
          uv pip install --system python-semantic-release
      - name: Run Semantic Release
        run: |
          cd service
          semantic-release version
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
