name: Release

on:
  workflow_run:
    workflows: ["Ruff, Test"]
    types:
      - completed
    branches: [master]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "service/pyproject.toml"
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          directory: ./service
