name: Ruff, Test

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "service/**"
      - ".github/workflows/test.yml"

jobs:
  ruff:
    if: ${{ !contains(github.event.head_commit.message, '[release]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2

  test:
    if: ${{ !contains(github.event.head_commit.message, '[release]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "service/pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "./service/uv.lock"
      - name: Install the project
        working-directory: ./service
        run: uv sync --all-extras --dev
      - name: Run tests
        working-directory: ./service
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: PYTHONPATH=$PYTHONPATH:. uv run pytest
      - name: Run pre-commit
        working-directory: ./service
        run: uv run pre-commit run --all-files
