name: Ruff, Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        working-directory: ./service
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip compile pyproject.toml > requirements.txt
          uv pip install --system -r requirements.txt
      - name: Run tests
        working-directory: ./service
        env:
          OPENAI_API_KEY: fake
          ANTHROPIC_API_KEY: fake
        run: pytest
